### PR TITLE
update 2

### PR DESCRIPTION
**Pull request by Warsheep-GER**
its so much 
added some cmd 2 times, 1 for exilemod with toastnotification and 1 for standard arma 3 ;)
test all  ,hope thats i dont missed any. 
and i need the playermenu /and the adminowncommand if u opend the atk without click any button ^^

### CODE REVIEW

**Comment by Warsheep-GER** [comment]
added some cmd 2 times, 1 for exilemod with toastnotification and 1 for standard arma 3 ;)

**Comment by ole1986** [comment]
exile_giveheal and exile_givekill should be named "giveheal" and "givekill" and should be a part of the the global system (not inside theExile extension).

**Comment by ole1986** [comment]
Could also not verify for what the adminowncommand is used for - please be more descriptive.

Also if you need to change the "player" register - feel free to amend so in the client files.

Of course I can not give you a guarantee that all your changes get applied.. But you chances are good :)

**Comment by Warsheep-GER** [comment]
giveheal givekill i missed for the standad . will do it soon. (for me its the exile port important ^,^) 

adminowncmd are commands for the admin itself where u dont need to select any kind of list .
like    login / healself / godmod / copy position in clipboard 

i just groups listed all commands to 
- adminown command for the admin itself (no own menu jet)
- players commands for selectet player (players menu)
- vehicles command for selectet/oncursor vehicle (vehicle menu)

ya thats i know, i shared all the stuff directly from my server so ther is some unfinished stuff too.

**Comment by ole1986** [comment]
Good that you are motivated to get those things done..

But please keep in mind because of issue #4 some parts may change in future.

I actually do not know yet if I keep the strings like "getplayers", "login" the way they are now...

Just telling - maybe they become number or Hercules to proper manage the permissions for moderators and Admins....

For example 

0xF0001 - 0xF9999 are Admin commands
And
0x00001 - 0x09999 are moderator commands

And later there are guest commands!? Using a different number block

**Comment by Warsheep-GER** [comment]
if they change then i need to rework just a littl bit, the funktion will not realy change itself. 

commands like getplayers are better for scripting bec u know what the command do if u read it, for 0xF0001 u need to search or a list with all to know what the command do . for using the atk its no intressting how the comand called.

u know when u update the issu #4  like 2 days or 2 weeks? if it soon i will stop to add new think and just search bugs

**Comment by Warsheep-GER** [comment]
ill think i will wait for the issu #4 update. and then do a new fork . so this pull u can delet . i will include this stuff in the new system then

**Pull request closed without merging**
