### PR TITLE
first update

### PR DESCRIPTION
**Pull request by Warsheep-GER**
some changes/additions ec. 
read commits
dont know what to say ;)

### CODE REVIEW

**Comment by ole1986** [comment]
Thank you for your pull request.

I noticed you have replace the "Exile Respect" button with one of yours.

I personally would keep this, espacially when its a fresh server I do not want to collect respect point until can buy helis to test several things..

So what to you think of the idea mentioned in #4 ?

**Comment by Warsheep-GER** [comment]
i dont replaced it just add the AdminToolkit_hasPermission for it . look line 65-68 ;) 
all buttons from you stay. i just renamed some bec it was to long for the button.  and any admin know thats he is in the exile game :D

**Comment by ole1986** [comment]
Ah, I see! Great let me test it and then we are good to go and implement... You want me to mention you on Exile forum?

**Comment by Warsheep-GER** [comment]
ok :D
ya if u canhelp me why not

**Comment by Warsheep-GER** [comment]
umm its shared all my changes ^^
its just for the adminowncommand like godemode/money/respect , think its a good idea for show this stuff on menuopend screen . when nothing is showed at the moment

**Comment by ole1986** [comment]
moved to  #5

**Pull request closed without merging**
